#!/usr/bin/env ruby

require "school"

if ARGV.length == 0 || %w[--help -h].include?(ARGV[0])
  puts "Usage #$0 FILE"
  exit
end

input_file  = ARGV[0]
output_file = input_file.split('/').last.split('.')[0..-2].join('.')

unless File.exist?(input_file)
  warn "error: Input file (#{input_file}) does not exist!"
  exit 1
end

if File.exist?(output_file)
  warn "error: Output file (#{output_file}) already exists!"
  exit 1
end

dsl = School::DSL.new
dsl.execute do
  eval(open(input_file).read, binding, input_file)
end

bytecode = dsl.bytecode

File.open(output_file, 'w') do |f|
  f.print bytecode
end
